// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DefaultRoutesController from "./default_routes_controller"
import RouterConfigFormController from "./router_config_form_controller"
application.register("default-routes", DefaultRoutesController)
application.register("router-config-form", RouterConfigFormController)
